### ISSUE TITLE
Intercept supplements

### ISSUE THREAD

**Issue by benthestatistician** [benbhansen-stats/propertee#205]
Implement the following to create supplemental intercept and moderator coefficients from control-condition observations.  These steps are to replace those described in the current estfun_DA spec under the heading "replacement intercepts," creating supplemental rather than replacement coefficients.[^1]   This is intended as an action issue, but the action steps laid out below are open to discussion and potential revision (at least at the outset). 

[^1]: That is, for now we assume that whatever overall intercept, subgroup-specific intercept and/or continuous moderator slope coefficients that may have been fitted with the main `lmitt()` regression will be kept in the `teeMod` object's coefficient vector, will have columns in the corresponding estfun matrix and so forth.  We may later decide to edit down the coefficient and related objects returned by `lmitt()` and incorporated into the `teeMod`, but that will be a part of a separate process. 

## to-do's

- [x] Inside of `lmitt.f()`:
- Create a model matrix (or one-sided model formula) for the Q-sample as follows:
	- for `rhstype == "intercept"`,  a single column of 1s, `(Intercept)`, as induced by model formula `~1`. 
	- for `rhstype == "continuous"`, a column of 1s and a column of the moderator, as induced by `~1+m`. 
	- for `rhstype == "categorical"`, a one-hot encoding of the moderator, as induced by `~0+m`. 
- Create case weights as follows:
	- for `absorb=FALSE`, take weights as given, but zero out weights outside the control group
	- for `absorb=TRUE`, create [one-way fixed effect weights](https://github.com/benbhansen-stats/propertee/wiki/Fixed-effects-&-overlap-weights) from given weights $\{\check{w}_i:i\}$, then zero out weights outside the control group
- Create a one- or two-column matrix response as follows:
	-  in column 1, the lmitt model's response variable, with column name equal to whatever's on the left-hand side of the lmitt model formula
	- in column 2, the `cov_adj()` predictions, if present.  If so, this column bears the name of the cov_adj model.   
- The matrix response is then regressed on the model matrix as above. The resulting coefficients are to be stored with the `teeMod`, perhaps by concatenation to the right of the existing coefficients or potentially by addition of a new slot.  If concatenating to the existing coefficient vector, mimic the naming scheme that `estfun.mlm()` uses to flatten dimnames of multivariate regression coefficient matrices into names for the same vector of coefficients, stripped of its dimension attribute. 

- [x] Inside of `as.lmitt()`:
- Create case weight as for ~~`absorb=TRUE`~~`absorb=FALSE` as in `lmitt.f()` as described above, ie given weights within control group and 0 weights outside of it  
- Create a one- or two column matrix response as in `lmitt.f()` as described above, with similar names 
- For now, create model matrix/one-sided formula as for `rhstype == intercept` above  
- (To explore later: to create intercept-supplement model matrix, pass `model.matrix()` the same formula RHS as was passed to the `lm()`, treatment variable and everything.  After fitting,  remove coefficients that come back NA.  This may in many or most cases leave coefficients precisely comparable to what the `lmitt.f()` procedure described above would have done, as the right-hand side terms that are the treatment variable or are interacted with the treatment variable will have to come back NA. This concept may also be combinable with touching up the formula that was passed to the `lm()` by removing RHS terms that we recognize as involving the intercept.) 

- [x] In `estfun.lmitt()`:
- cbind what `estfun.lmitt()` now produces to the value of `estfun.mlm` as applied to our supplemental regression.
- [x] In bread methods: 
- For $`\tilde{A}_{22}`$, return block diagonal matrix with upper left block equal to current $A_{22}$ matrix associated with a `teeMod`, and lower right block equal to the $A$ matrix of the supplemental regression, scaled so as to match the scaling applied to the upper-left block
- For $`A_{21}`$, rows corresponding to coefficients of the y-on-xes regression are all 0. Rows corresponding to coefficients of the cmod-on-xes regression have entries $n_{Q}^{-1}\sum_Q g'(\vec{x}_i\hat\beta)\vec{x}_i$
- [x] In show and summary methods for `teeMod`s:
- Add to coefficient displays supplemental intercept coefficients for y-regressions (but not for cmod-regressions).
- [x] In estfun_DA spec: 
- update to reflect the above changes
- roll back stuff rotating coefficients and A matrices for subgrouping moderators
- as appropriate, roll back "replacement" intercept concept.

## other issues superseded by this issue

- Intercept coefficient replacements for teeMods  #195.  For the time being we're adding but not subtracting coefficients.  (Despite some [discussion there](https://github.com/benbhansen-stats/propertee/issues/195#issuecomment-2495650957) about coefficient names with possible future relevance.)
-  intercept/main effect transformation for teeMods with a subgroup moderator  #196.  The current proposal generates subgroup-specific intercepts with the informative labeling in a more direct manner.
- Intercept for lmitt(absorb=T)  #188. (Josh W's comments about implementation of that proposal, eg [here](https://github.com/benbhansen-stats/propertee/issues/188#issuecomment-2439044470) remain relevant.)

**Comment by benthestatistician** [comment]
I've assigned this to Josh W but I'm hoping that @josherrickson will be able to review & potentially help.  Closes #188, #195 and #196.

**Comment by jwasserman2** [comment]
This breaks about 100 different tests, but I've pushed the code changes without addressing them/adding tests for all new functionality to the `i205_intercept` branch. You can try the functionality out there @benthestatistician 

Some newly failing tests to discuss (@josherrickson as well):
1) In [`test.lmitt.R`](https://github.com/benbhansen-stats/propertee/blob/55a515a80b924eb99a91bd19a35fb67cb9041827/tests/testthat/test.lmitt.R#L163): `lmitt()` currently allows for fitting to a multi-level treatment without a `dichotomy`. How should one-way fixed effects weights be computed then?

### Other questions about functionality:
1) For naming the added elements of the coefficients vector, `offset` is much simpler than the name of the covariance adjustment model object (and technically, the user doesn't even need to pass a named model object to `cov_adj()`). I'm not tied to the use of `offset`, but are we tied to using something referencing the model object?
1) Do the changes to `estfun.teeMod()` have to be altered at all for design-based variance estimation?
1) Currently, we set `absorb=FALSE` by default in `as.lmitt()`. Do we want to change that?
1) Do we want to take a stance on using our `ate()/ett()` weighting functions with `absorb=TRUE` through a message or warning?

**Comment by benthestatistician** [comment]
Replying to points 0-5 of JE comment immediately above:
 
0\. `lmitt()` and non-binary treatments

Note that it's really just nonbinary numeric treatments, i.e. continuous treatments, that we're discussing (a11a55e). The fixed effects weighting concept doesn't make sense in these cases, I'm afraid, and I don't see any clear replacement for it.  Some possibilities, in decreasing preference order:
i. Calculate and report intercept supplements as in other cases, using
  a.  `y_adj = y - z * tauhat` in lieu of `y`
  b. the entire sample in lieu of the control group
  c. under `absorb=T`, user-provided weights instead of one-way fixed effects weights
ii. let this be our cue to abandon support for nonbinary numeric treatments
iii. refrain from computing or reporting intercept supplements in this case

In possibility (i), no subjects are zeroed out before performing the regression that generates the intercept supplements.  The $`\hat{\tilde{A}}_{22}`$ matrix representing this situation lacks the block diagonal structure of the A matrices we compute otherwise: in the rows for `y_adj` intercept supplement(s), $\tau$ columns have $`-n_{\mathcal{Q}}^{-1}\sum_{i \in \mathcal{Q}}\check{w}_{i}z_i`$, not 0. (Rows for `cov_adj` intercept supplements remain 0 in $\tau$ columns, ie in the off-diagonal block.)    The $`\hat{A}_{21}`$ matrix is structured as in other cases. 

1. Point taken; thanks. But rather than `offset`, I say we name those added elements `cov_adj`, which is more specific to the offsets we have in mind. 
2. Yes and no. The estfun matrices as will be reported by `estfun.mlm()` are about as they should be for design- as well as model-based estimation, but there are 2 issues being kicked down the road for later: (a) I'm not 100% clear on how design-based variance and covariance estimation should work for these in the small-block case; (b) in the `absorb=T` scenarios, where one-way fixed effect weights are applied to the control group, arguably the corresponding estfun should instead apply overlap weights, figured with block parameters $p_{b}$ as inferred from the StudySpec rather than $\hat{p}_{b}$ as estimated from the realized allocation within the block. But the same argument leading to (b) suggests parallel modifications to the primary `estfun.teeMod()` material to be returned under `absorb=T` scenarios. As I don't see a role for this argument in any of our current paper projects, I see developing it, implementing it in software and seeing where it leads as a future project. 
3. No, I think we should stick with `absorb=T` being a `lmitt.f()`thing only
4. I lean no, in that case let the user be. (I myself don't see a role for doing both at the same time, but the Schochet et al JASA 2021 paper seems to, and I'm not sure the matter rises to the level of needing our warning messages to contradict them.)  I could be persuaded otherwise if this were somehow creating trouble downstream -- is it? 

Please don't hesitate to update inline code comments as you update the code itself (edfdd3d does ithis in one place where an old comments of JE's would have no longer made sense on its own).  This is of course minor; overall, thanks for this quite nice work. I much appreciate the tests to verify the calculations as well as the structures and methods.

**Comment by benthestatistician** [comment]
f90676a on branch i205_intercept updates the estfun_DA spec with these concepts.   In a few places the concept sharpened in the course of spec development, here are the ones that may call for some code adjustments and that come to mind:

1.   For `lmitt.f(y~m, absorb=T)`, the spec now calls for case weights determining intercept supplements to be calculated differently according as the moderator `m` is continuous or categorical.  If `m` is continuous, it's the same as when there's only a main effect, i.e. block fixed effects weights that are zeroed out outside of the control group; if `m` is categorical,  the block fixed effects weights are calculated separately for each subgroup (and then zeroed out for non-controls).  This differs from what's currently implemented in `lmitt.f()` on the i205_intercept branch, [lmitt.R#L376-L383](https://github.com/benbhansen-stats/propertee/blob/f90676affcff19b1523841fdc93ff6776c56f701/R/lmitt.R#L376-L383).  (And, to be fair, from what's called for in the statement of this issue.) 
2.  For now, nothing in the spec about continuous treatments.  Those questions remain.

**Comment by jwasserman2** [comment]
When it comes to estimates of treatment effects for continuous treatments, I think this quote from [Díaz and van der Laan (2013)](https://www.degruyter.com/document/doi/10.1515/jci-2012-0005/html) makes a key point about how their guarantees differ from the guarantees provided by estimates of dichotomized treatments:

> The most widely known method for estimation of the CDRC [causal dose-response curve] for continuous exposures is the so-called marginal structural model (MSM) framework, which was first proposed by Robins et al. [16]. In addition to
the structural causal assumptions required for identifiability, the veracity of the statistical claims of MSM
analyses relies on the correct specification of a parametric model for the CDRC, that is, the model needs to
contain the true dose–response curve

My interpretation is that we would be committing to assuming the effect of treatment is truly linear, which we are not obligated to do in the case of dichotomized treatments. The authors continue by saying that others ((Neugebauer and van der Laan, 2007)[https://www.sciencedirect.com/science/article/pii/S0378375806000334?casa_token=CiquGq7HeoIAAAAA:qZ0MhCoyu86D2WCvp0-0pMy3yxtN5bWxAx3SGCcu5ZkzdU86wpGKFY_uzVrCjLfB7zEtpg]) relaxed the assumption of correct specification by re-defining the estimand.

This also does not touch on the complexities of propensity score estimation for continuous treatments, which I've found to be intuitively explained [this paper](https://arxiv.org/pdf/2309.00706) by Ed Kennedy and others. Some key ideas from their work:
* Violations of positivity are likely in the case of continuous treatments, since it may not be possible for subjects to receive every possible value of the treatment. This leads to the use of propensity score trimming
* Proportion of trimmed subjects is itself subject to uncertainty in the propensity score, requiring additional attention for correct inference
* Parametric propensity score models perform poorly when probability of a certain value of treatment is small. This leads to the use of nonparametric or semiparametric estimation
* ATE in the propensity-trimmed population cannot be estimated exactly, which leads to targeting a similar but estimable estimand

I interpret these points as saying that we would be committing ourselves to estimands that have alternative interpretations than those we commit to with dichotomized treatments.

From my understanding, it does seem that we generally would not be on the same footing by allowing users to estimate treatment effects using `lmitt()` with a continuous treatment. They can certainly form `Design` objects and dichotomize a treatment, though that does not necessarily the violations of positivity described above, and I don't think we intend to commit ourselves to propensity score-trimming tools in the near future. My vote would be to force users to error if the treatment passed to `lmitt()` isn't dichotomized

**Comment by jwasserman2** [comment]
At the end of `lmitt.Rd` with the new additional documentation, add a parenthetical to the `absorb` statement saying with a categorical moderator variable, weights $\hat{\pi}\_{s}$ are defined with $\hat{\pi}\_{bs}$ defined separately with each category $b$.
